exec-once = hyprctl dispatch focusmonitor HDMI-A-1
exec-once = hyprctl dispatch workspace 2

exec-once = [workspace 2 silent monitor HDMI-A-1 float size 80% 85% move 0% 0% pseudo] kitty --title Btop -e btop
exec-once = [workspace 2 silent monitor HDMI-A-1 float size 70% 80% move 80% 0% pseudo] kitty --title Fastfetch -e fastfetch
exec-once = [workspace 2 silent monitor HDMI-A-1 float size 60% 50% move 0% 50% pseudo] kitty

r HDMI-A-1 float size 35% 40% move 65% 50% pseudo] kitty --title Cmatrix -e cmatrix
exec-once = [workspace 2 silent monitor HDMI-A-1 float size 35% 40% move 65% 60% pseudo] kitty --title Cava -e cava
exec-once = [workspace 2 silent monitor HDMI-A-1 float size 35% 40% move 65% 80% pseudo] kitty --title TtyClock -e tty-clock -c -C 6

exec-once = hyprctl dispatch workspace 3

exec-once = [workspace 3 silent monitor HDMI-A-1 float size 80% 85% move 0% 0% pseudo] zen-browser https://music.youtube.com/
exec-once = [workspace 3 silent monitor HDMI-A-1 float size 35% 40% move 65% 0% pseudo] kitty --title Cava -e cava
exec-once = [workspace 3 silent monitor HDMI-A-1 float size 35% 40% move 65% 45% pseudo] kitty --title Pipes -e pipes.sh -f 100 -p 2

exec-once = hyprctl dispatch workspace 2

